# Site settings
title: HuaQiang Yan
description: HuaQiang Yan
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: HuaQiang Yan
user_description: I'm a Software Engineer.
user_title: Software Engineer
email: huaqiangyan@163.com
# twitter_username: lorem_ipsum
# github_username:  lorem_ipsum
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src' , 'node_modules']
